# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0013_auto_20180808_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='run_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('error', 'Error'), ('running', 'Running'), ('archiving', 'Archiving'), ('complete', 'Complete')], default='idle', max_length=50, verbose_name='Run Status'),
        ),
    ]
